- name: openai/gemini-2.5-pro
  edit_format: diff-fenced
  use_temperature: 0.3

- name: openai/gemini-2.5-flash
  edit_format: diff-fenced
  use_temperature: 0.3

- name: openai/gemini-2.5-flash-lite
  edit_format: diff-fenced
  use_temperature: 0.3
