# - name: openai/GLM-4.5
#   edit_format: diff
#
# - name: openai/qwen3-235b-a22b-thinking
#   edit_format: diff
#
# - name: openai/qwen3-coder
#   edit_format: diff
#
# - name: openai/qwen3-235b-a22b
#   edit_format: diff
#   use_temperature: true
#
# - name: openai/kimi-k2
#   edit_format: diff
#
# - name: openai/DeepSeek-R1-0528
#   edit_format: diff
#
# - name: openai/DeepSeek-V3-0324
#   edit_format: diff
#
# - name: openai/openrouter
#   edit_format: diff

- name: openai/gemini-2.5-pro
  edit_format: diff-fenced

- name: openai/gemini-2.5-flash
  edit_format: diff-fenced

- name: openai/gemini-2.5-flash-lite
  edit_format: diff-fenced
