- name: openai/GLM-4.5
  edit_format: diff

- name: openai/openai/qwen3-235b-a22b-thinking
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/qwen3-coder
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/qwen3-235b-a22b
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/kimi-k2
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/DeepSeek-R1-0528
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/DeepSeek-V3-0324
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.3
    top_p: 0.95

- name: openai/gemini-2.5-pro
  edit_format: diff-fenced

- name: openai/gemini-2.5-flash
  edit_format: diff-fenced
