- name: openai/DeepSeek-R1-0528
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/DeepSeek-V3-0324
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.3
    top_p: 0.95

- name: openai/DeepSeek-R1-0528-d
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/DeepSeek-V3-0324-d
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.3
    top_p: 0.95

- name: openai/DeepSeek-R1
  edit_format: diff
  use_temperature: true
  extra_params:
    temperature: 0.6
    top_p: 0.95

- name: openai/gemini-2.5-pro
  edit_format: diff-fenced

- name: openai/gemini-2.5-flash
  edit_format: diff-fenced
